language: java
sudo: false
os:
  - linux
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn clean install -Dgpg.skip=true
notifications:
  email: false