language: java
sudo: required
before_install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
   - echo $JAVA_HOME
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: osx
      env: JAVA_HOME=/usr/libexec/java_home
install:
  - mvn clean install -DskipTests=true
script:
  - mvn clean install
notifications:
  email: false
