language: java
sudo: false
os:
  - linux
  - osx
before_install:
    # Work around https://github.com/travis-ci/travis-ci/issues/2317
  - if \[ "$TRAVIS_OS_NAME" = linux \]; then jdk_switcher use oraclejdk8; fi
  - if \[ "$TRAVIS_OS_NAME" = osx \]; then brew update; fi
install: mvn install -DskipTests=true -Dgpg.skip=true
script:
  - mvn clean install -Dgpg.skip=true
notifications:
  email: false