language: java
sudo: required
dist: trusty
os:
  - linux
install: mvn install -DskipTests=true -Dgpg.skip=
jdk:
  - openjdk8
  - oraclejdk8
script:
  - mvn clean install -Dgpg.skip=true
notifications:
  email: false