language: java
sudo: required
dist: trusty
group: edge
os:
  - linux
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
script:
  - mvn clean install -Dgpg.skip=true
notifications:
  email: false