language: java
sudo: required
before_install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
   - echo $JAVA_HOME
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk9
      sudo: required
      dist: trusty
      group: edge
os:
  - linux
  - osx
install: mvn install -DskipTests=true -Dgpg.skip=true
script:
  - mvn clean install -Dgpg.skip=true
notifications:
  email: false