version: '{branch}-{commit}'
os: Windows Server 2012
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: choco install maven
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean install -DskipTests=true
test_script:
  - mvn clean install
cache:
  - C:\Users\appveyor\.m2